from typing import Protocol
from uuid import UUID

from domain.entities.job_application import JobApplication


class JobApplicationRepository(Protocol):
    async def add(self, entity: JobApplication) -> None: ...

    async def get_all(self) -> list[JobApplication]: ...

    async def get_by_id(self, id: UUID) -> JobApplication | None: ...

    async def update(self, entity: JobApplication) -> None: ...

    async def delete(self, entity: JobApplication) -> None: ...
