"""Add JobApplicationDocument

Revision ID: 26050602c180
Revises: 8bfddea457d0
Create Date: 2026-02-03 11:42:17.389707

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26050602c180"
down_revision: Union[str, Sequence[str], None] = "8bfddea457d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_documents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content", sa.LargeBinary(), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=False),
        sa.Column("job_application_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_application_id"], ["job_applications.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_application_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("application_documents")
    # ### end Alembic commands ###
