"""Init migration

Revision ID: abd89ee8459c
Revises:
Create Date: 2026-01-28 01:51:09.751784

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "abd89ee8459c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_applications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("role_name", sa.String(length=255), nullable=False),
        sa.Column("posting_url", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "APPLIED",
                "INTERVIEWED",
                "OFFERED",
                "ACCEPTED",
                "REJECTED",
                name="applicationstatus",
            ),
            nullable=False,
        ),
        sa.Column("work_model", sa.String(length=50), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_compensations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("min_salary", sa.Integer(), nullable=True),
        sa.Column("max_salary", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column(
            "employment_type",
            sa.Enum("B2B", "PERMANENT", "CONTRACT", name="employmenttype"),
            nullable=False,
        ),
        sa.Column("job_application_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_application_id"], ["job_applications.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_compensations")
    op.drop_table("job_applications")
    # ### end Alembic commands ###
